CREATE TABLE ADDRESS (
  ADDRESS_ID NUMBER(19) AUTO_INCREMENT  PRIMARY KEY,
  ADD_ONE VARCHAR(250) NOT NULL,
  ADD_TWO VARCHAR(250),
  CITY VARCHAR(250),
  STATE VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(250)  NOT NULL,
  ZIP_CODE NUMBER(19) NOT NULL
);



CREATE TABLE USER(
 USER_ID NUMBER(19)AUTO_INCREMENT PRIMARY KEY,
 USER_NAME VARCHAR(250)NOT NULL,
 EMAIL VARCHAR(250)NOT NULL,
 PHONE_NO NUMBER(19)NOT NULL,
 ADDRESS_ID NUMBER(19)NOT NULL,
 USER_TYPE VARCHAR(250)NOT NULL
 );

 
 CREATE TABLE FEEDBACK(
 FEEDBACK_ID NUMBER(19)AUTO_INCREMENT PRIMARY KEY,
 FEEDBACK_MESSAGE VARCHAR(250)NOT NULL,
 USER_ID NUMBER(19)NOT NULL
 
 );